/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDoctorsRouteImport } from './routes/_authenticated/doctors'
import { Route as AuthenticatedDonateRouteImport } from './routes/_authenticated/donate'
import { Route as AuthenticatedMatchingRouteImport } from './routes/_authenticated/matching'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorsRoute = AuthenticatedDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonateRoute = AuthenticatedDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchingRoute = AuthenticatedMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/donate': typeof AuthenticatedDonateRoute
  '/matching': typeof AuthenticatedMatchingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/donate': typeof AuthenticatedDonateRoute
  '/matching': typeof AuthenticatedMatchingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctors': typeof AuthenticatedDoctorsRoute
  '/_authenticated/donate': typeof AuthenticatedDonateRoute
  '/_authenticated/matching': typeof AuthenticatedMatchingRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/appointments'
    | '/dashboard'
    | '/doctors'
    | '/donate'
    | '/matching'
    | '/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/appointments'
    | '/dashboard'
    | '/doctors'
    | '/donate'
    | '/matching'
    | '/notifications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/appointments'
    | '/_authenticated/dashboard'
    | '/_authenticated/doctors'
    | '/_authenticated/donate'
    | '/_authenticated/matching'
    | '/_authenticated/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors': {
      id: '/_authenticated/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donate': {
      id: '/_authenticated/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof AuthenticatedDonateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matching': {
      id: '/_authenticated/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AuthenticatedMatchingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorsRoute: typeof AuthenticatedDoctorsRoute
  AuthenticatedDonateRoute: typeof AuthenticatedDonateRoute
  AuthenticatedMatchingRoute: typeof AuthenticatedMatchingRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorsRoute: AuthenticatedDoctorsRoute,
  AuthenticatedDonateRoute: AuthenticatedDonateRoute,
  AuthenticatedMatchingRoute: AuthenticatedMatchingRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
